server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
 




spring:
   datasource:
      url: jdbc:mysql://rm-bp1l1k48yuka2xt1nvo.mysql.rds.aliyuncs.com:3306/marrydb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
      username: rootmarry
      password: GIChain@2018
      tomcat:
          max-active: 20
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver

    
   redis:
        host: 127.0.0.1
        port: 6379
        timeout: 30000ms
#mybaties配置
mybatis:
    type-aliases-package: com.door.match.entity
    mapper-locations: classpath*:/mapperxml/**.xml
    check-config-location: true
    configuration:
        map-underscore-to-camel-case: true

logging:
    path: ./log
    level:
        com.door.match: info

#小程序登陆
wx:
  miniprogram:
    login: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
#小程序id
    appid: wx0d4b32bb35f376e4
#小程序secret
    secret: 089cfb98886f1b96295b228800b9d6f5
    #回调域名
    callbackip: http://dubindev.nat100.top
     #商户号
    mchid: 1524818501
     #微信支付key
    key: fxAA3l43LmYz0Vdym58nD5wITClJBmxo